# Generated by Django 2.2.4 on 2019-08-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0002_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
