# Generated by Django 3.0.3 on 2020-03-15 15:29

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_project_deployment_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 29, 4, 158161, tzinfo=utc)),
        ),
    ]
