# Generated by Django 2.2.4 on 2019-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('purchase_link', models.URLField(blank=True, null=True)),
                ('favourite_passage', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
