# Generated by Django 3.0.3 on 2020-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('R', 'Read'), ('CR', 'Currently Reading')], default='CR', max_length=2),
        ),
    ]
