# Generated by Django 3.0.3 on 2020-03-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200314_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_date']},
        ),
    ]
