# Generated by Django 2.2.4 on 2019-08-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
