# Generated by Django 3.0.3 on 2020-02-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('short', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('target', models.URLField()),
            ],
        ),
    ]
